call solve1.bat \lp_solve\miplib3\10teams.mps
call solve1.bat \lp_solve\miplib3\air03.mps
call solve1.bat \lp_solve\miplib3\air04.mps
call solve1.bat \lp_solve\miplib3\air05.mps
call solve1.bat \lp_solve\miplib3\arki001.mps
call solve1.bat \lp_solve\miplib3\bell3a.mps
call solve1.bat \lp_solve\miplib3\bell5.mps
call solve1.bat \lp_solve\miplib3\blend2.mps
call solve1.bat \lp_solve\miplib3\cap6000.mps
call solve1.bat \lp_solve\miplib3\dano3mip.mps
call solve1.bat \lp_solve\miplib3\danoint.mps
call solve1.bat \lp_solve\miplib3\dcmulti.mps
call solve1.bat \lp_solve\miplib3\dsbmip.mps
call solve1.bat \lp_solve\miplib3\egout.mps
call solve1.bat \lp_solve\miplib3\enigma.mps
call solve1.bat \lp_solve\miplib3\fast0507.mps
call solve1.bat \lp_solve\miplib3\fiber.mps
call solve1.bat \lp_solve\miplib3\fixnet6.mps
call solve1.bat \lp_solve\miplib3\flugpl.mps
call solve1.bat \lp_solve\miplib3\gen.mps
call solve1.bat \lp_solve\miplib3\gesa2.mps
call solve1.bat \lp_solve\miplib3\gesa2_o.mps
call solve1.bat \lp_solve\miplib3\gesa3.mps
call solve1.bat \lp_solve\miplib3\gesa3_o.mps
call solve1.bat \lp_solve\miplib3\gt2.mps
call solve1.bat \lp_solve\miplib3\harp2.mps
call solve1.bat \lp_solve\miplib3\khb05250.mps
call solve1.bat \lp_solve\miplib3\l152lav.mps
call solve1.bat \lp_solve\miplib3\lseu.mps
call solve1.bat \lp_solve\miplib3\miplib.cat
call solve1.bat \lp_solve\miplib3\miplib3.zip
call solve1.bat \lp_solve\miplib3\misc03.mps
call solve1.bat \lp_solve\miplib3\misc06.mps
call solve1.bat \lp_solve\miplib3\misc07.mps
call solve1.bat \lp_solve\miplib3\mitre.mps
call solve1.bat \lp_solve\miplib3\mod008.mps
call solve1.bat \lp_solve\miplib3\mod010.mps
call solve1.bat \lp_solve\miplib3\mod011.mps
call solve1.bat \lp_solve\miplib3\modglob.mps
call solve1.bat \lp_solve\miplib3\mps_format
call solve1.bat \lp_solve\miplib3\noswot.mps
call solve1.bat \lp_solve\miplib3\nw04.lp
call solve1.bat \lp_solve\miplib3\p0033.mps
call solve1.bat \lp_solve\miplib3\p0201.mps
call solve1.bat \lp_solve\miplib3\p0282.mps
call solve1.bat \lp_solve\miplib3\p0548.mps
call solve1.bat \lp_solve\miplib3\p2756.mps
call solve1.bat \lp_solve\miplib3\pe.cfg
call solve1.bat \lp_solve\miplib3\pk1.mps
call solve1.bat \lp_solve\miplib3\pp08a.mps
call solve1.bat \lp_solve\miplib3\pp08aCUTS.mps
call solve1.bat \lp_solve\miplib3\qiu.mps
call solve1.bat \lp_solve\miplib3\qnet1.mps
call solve1.bat \lp_solve\miplib3\qnet1_o.mps
call solve1.bat \lp_solve\miplib3\references
call solve1.bat \lp_solve\miplib3\rentacar.mps
call solve1.bat \lp_solve\miplib3\result4'.txt
call solve1.bat \lp_solve\miplib3\rgn.mps
call solve1.bat \lp_solve\miplib3\rout.mps
call solve1.bat \lp_solve\miplib3\set1ch.mps
call solve1.bat \lp_solve\miplib3\seymour.mps
call solve1.bat \lp_solve\miplib3\stein27.mps
call solve1.bat \lp_solve\miplib3\stein45.mps
call solve1.bat \lp_solve\miplib3\test.bat
call solve1.bat \lp_solve\miplib3\test0.bat
call solve1.bat \lp_solve\miplib3\test1.bat
call solve1.bat \lp_solve\miplib3\test3.bat
call solve1.bat \lp_solve\miplib3\test4'.bat
call solve1.bat \lp_solve\miplib3\test4.bat
call solve1.bat \lp_solve\miplib3\vpm1.mps
call solve1.bat \lp_solve\miplib3\vpm2.mps
